name: Kernel Build Check

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs: {}
  workflow_call:
    inputs: {}

jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        kernel_config:
          # Android 13 - Kernel 5.15 LTS (Latest)
          - android_version: "android13"
            kernel_version: "5.15"
            sub_level: "X"
            os_patch_level: "lts"

    name: Build Check
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.kernel_config.android_version }}
      kernel_version: ${{ matrix.kernel_config.kernel_version }}
      sub_level: ${{ matrix.kernel_config.sub_level }}
      os_patch_level: ${{ matrix.kernel_config.os_patch_level }}
