name: Small Github Actions test

permissions:
  contents: write
  actions: write

on:
    workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - id: testing
        run: |
          ls -l 
          echo ${PWD}
          
