name: Small Github Actions test

permissions:
  contents: write
  actions: write

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - id: testing
        run: |
          ls -l 
          echo ${PWD}
          
